name: CompileOpenclashTest

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select branch to compile'
        required: true
        default: 'master'
        type: choice
        options:
          - master
          - dev
          - test

jobs:
  Get-Version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Get Version
        id: version
        run: |
          echo "version=$(grep 'PKG_VERSION:=' ./luci-app-openclash/Makefile |awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT

  Compile:
    runs-on: ubuntu-latest
    needs: Get-Version
    strategy:
      matrix:
        target:
          - { name: ipk, sdk_url: "https://mirrors.pku.edu.cn/openwrt/releases/22.03.0/targets/x86/64/openwrt-sdk-22.03.0-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz", sdk_tar: "SDK.tar.xz", sdk_backup_tar: "SDK.tar.bz2", sdk_dir: "SDK", artifact_pattern: "luci-app-openclash_*.ipk" }
          - { name: apk, sdk_url: "snapshot", sdk_tar: "SNAPSDK.tar.zst", sdk_backup_tar: "SNAPSDK.tar.zst", sdk_dir: "SNAPSDK", artifact_pattern: "luci-app-openclash-*.apk" }
    steps:
      - name: Checkout OpenClash Source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install Dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get -y install curl git tar zstd python3 python3-pyelftools python3-setuptools

      - name: Download SDK
        run: |
          mkdir -p tmp
          if [ "${{ matrix.target.name }}" = "ipk" ]; then
            if ! curl -SLk --connect-timeout 30 --retry 2 "${{ matrix.target.sdk_url }}" -o "./tmp/${{ matrix.target.sdk_tar }}"; then
              curl -SLk --connect-timeout 30 --retry 2 "https://archive.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2" -o "./tmp/SDK.tar.xz"
              cd tmp
              tar xjf ${{ matrix.target.sdk_backup_tar }}
              mv OpenWrt-SDK-* ${{ matrix.target.sdk_dir }}
            else
              cd tmp
              tar xf ${{ matrix.target.sdk_tar }}
              mv openwrt-sdk-* ${{ matrix.target.sdk_dir }}
            fi
          else
            BASE_URL="https://downloads.openwrt.org/snapshots/targets/x86/64/"
            SDK_NAME=$(curl -s $BASE_URL | grep -oE 'openwrt-sdk-x86-64[^"]+\.tar\.zst' | head -n 1)
            if ! curl -SLk --connect-timeout 30 --retry 2 "$BASE_URL/$SDK_NAME" -o "./tmp/${{ matrix.target.sdk_tar }}"; then
              BASE_URL2="https://mirrors.pku.edu.cn/files/openwrt/snapshots/targets/x86/64/"
              SDK_NAME=$(curl -s $BASE_URL2 | grep -oE 'openwrt-sdk-x86-64[^"]+\.tar\.zst' | head -n 1)
              curl -SLk --connect-timeout 30 --retry 2 "$BASE_URL2/$SDK_NAME" -o "./tmp/${{ matrix.target.sdk_tar }}"
            fi
            cd tmp
            zstd -d ${{ matrix.target.sdk_tar }}
            tar xf SNAPSDK.tar
            SDK_DIR=$(tar tf SNAPSDK.tar | head -n 1 | cut -d/ -f1)
            mv "$SDK_DIR" "${{ matrix.target.sdk_dir }}"
          fi

      - name: Copy OpenClash Source Codes
        run: |
          mkdir -p tmp/${{ matrix.target.sdk_dir }}/package/luci-app-openclash
          cp -rf ./luci-app-openclash/. tmp/${{ matrix.target.sdk_dir }}/package/luci-app-openclash/

      - name: Compile po2lmo
        run: |
          cd tmp/${{ matrix.target.sdk_dir }}/package/luci-app-openclash/tools/po2lmo
          make && sudo make install

      - name: Compile OpenClash
        run: |
          cd tmp/${{ matrix.target.sdk_dir }}
          if [ -f ../${{ matrix.target.sdk_tar }} ]; then
            make defconfig
          fi
          make package/luci-app-openclash/compile V=99

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openclash-${{ matrix.target.name }}
          path: tmp/${{ matrix.target.sdk_dir }}/bin/packages/x86_64/base/${{ matrix.target.artifact_pattern }}

  Create-Release:
    runs-on: ubuntu-latest
    needs: [Compile, Get-Version]
    permissions:
      contents: write
    env:
      PACKAGE_NAME: luci-app-openclash
    steps:
      - name: Download IPK Artifact
        uses: actions/download-artifact@v4
        with:
          name: openclash-ipk
          path: ./

      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: openclash-apk
          path: ./

      - name: Create Release Notes
        run: |
          cat > RELEASE_NOTES.md << 'EOF'
          # OpenClash Mod v${{ needs.Get-Version.outputs.version }}
          
          ### Instalasi For OpenWrt | ImmortalWrt
          # IPK
          ```bash
          opkg install ${{ env.PACKAGE_NAME }}*.ipk
          ```
          
          # APK
          ```bash
          apk add ${{ env.PACKAGE_NAME }}*.apk
          ```
          EOF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.Get-Version.outputs.version }}
          name: v${{ needs.Get-Version.outputs.version }}
          body_path: RELEASE_NOTES.md
          files: |
            luci-app-openclash_*.ipk
            luci-app-openclash-*.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}